version: '2'
services:
  nginx:
    tty: true
    image: eosystems/nginx-eosystems-local
    container_name: nginx-eosystems-local
    build: build/nginx-eosystems-local
    ports:
      - "80:80"
    networks:
      - default
      - eosystemsdocker_default
      - eopesdocker_default
    environment:
      url_eobackbone: eobackbone.local
      url_eopes: eopes.local

networks:
  eosystemsdocker_default:
    external: true
  eopesdocker_default:
    external: true
