version: '2'
services:
  nginx:
    tty: true
    image: nginx-eosystems
    container_name: nginx-eosystems
    build: build/nginx-eosystems
    ports:
      - "80:80"
    networks:
      - default
      - eosystemsdocker_default

networks:
  eosystemsdocker_default:
    external: true
