version: '2'
services:
  nginx:
    tty: true
    image: eosystems/nginx-eosystems
    container_name: nginx-eosystems
    build: build/nginx-eosystems
    ports:
      - "80:80"
    networks:
      - default
      - eosystemsdocker_default
      - eopesdocker_default
    environment:
      url_eobackbone: localhost
      url_eopes: eopes.local

networks:
  eosystemsdocker_default:
    external: true
  eopesdocker_default:
    external: true
